### ISSUE TITLE
Script tag placed at end of an HTML document prevents previewing and editing

### ISSUE THREAD

**Issue by bledwell** [plone/diazo#37]
Im using the CSS framework "Foundation"
The theming editor in Plone seems to have a bug that prevents a page from displaying in the editor and being able to edit its contents if theres a 
`<script>$(document).foundation();</script>` placed before the `</body>` tag of an HTML document. Which is what Foundation recommends.

When I activate the theme it works as expected and the pages get themed but if I were to go back to the theming editor "Site-Setup > Theming > Modify Theme" and select the HTML document that contains the script I get a spinning icon. This would be fine if I didn't make any mistakes when adding my rules but Id like to be able to go back in and edit via the theming editor.

Im running
Plone 4.3 
Diazo 1.1

Ive tried this in Safari, Chrome and FireFox all exhibit the same behavior.
![screen shot 2015-01-16 at 1 10 36 pm](https://cloud.githubusercontent.com/assets/4641090/5782497/1ddf2e16-9d81-11e4-93ae-74951d74cb08.png)

thanks,
Brian

**Comment by vangheem** [comment]
What versions of plone.app.theming and plone.resourceeditor are you using?
I believe there was a fix for this a long time ago in plone.resourceeditor.
That version should be at 1.0

On Fri, Jan 16, 2015 at 1:11 PM, Brian Ledwell <notifications@github.com>
wrote:

> Im using the CSS framework "Foundation"
> The theming editor in Plone seems to have a bug that prevents a page from
> displaying in the editor and being able to edit its contents if theres a
> <script>$(document).foundation();</script> placed before the </body> tag
> of an HTML document. Which is what Foundation recommends.
>
> When I activate the theme it works as expected and the pages get themed
> but if I were to go back to the theming editor "Site-Setup > Theming >
> Modify Theme" and select the HTML document that contains the script I get a
> spinning icon. This would be fine if I didn't make any mistakes when adding
> my rules but Id like to be able to go back in and edit via the theming
> editor.
>
> Im running
> Plone 4.3
> Diazo 1.1
>
> Ive tried this in Safari, Chrome and FireFox all exhibit the same behavior.
> [image: screen shot 2015-01-16 at 1 10 36 pm]
> <https://cloud.githubusercontent.com/assets/4641090/5782497/1ddf2e16-9d81-11e4-93ae-74951d74cb08.png>
>
> thanks,
> Brian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/diazo/issues/37>.
>



-- 
Nathan Van Gheem
Solutions Architect
Wildcard Corp

**Comment by bledwell** [comment]
OK, we can see that github has 1.0 but pypi's latest is 1.0b4, which is what we are running on the server.  Could you create the egg or should we?

**Comment by vangheem** [comment]
latest on pypi is 1.0: https://pypi.python.org/pypi/plone.resourceeditor/

On Wed, Jan 21, 2015 at 8:19 AM, Brian Ledwell <notifications@github.com>
wrote:

> OK, we can see that github has 1.0 but pypi's latest is 1.0b4, which is
> what we are running on the server. Could you create the egg or should we?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/diazo/issues/37#issuecomment-70844308>.
>



-- 
Nathan Van Gheem
Solutions Architect
Wildcard Corp

**Comment by bledwell** [comment]
Nathan.. Thanks! That worked, we updated the plone.resource & plone.resourceeditor eggs and now I can add my script tag without it the theming editor hanging up.

thanks again
Brian
