### ISSUE TITLE
runtime execution of if-statements

### ISSUE THREAD

**Issue by loechel** [plone/diazo#39]
diazo is very nice on execution model, but there is one misleading Point on execution of if Statements

example:

`<theme href="http://example.org/index.html if="$readNetwork" />`

Diazo tries to read the remote source even if the if Statement validates to false. As any conditional this should only be done if the if-statement is true.

**Comment by seocam** [comment]
@loechel if I got it right, the conditional rules works for every rule except theme?

I don't see any examples of <theme> using ifs in the docs (http://docs.diazo.org/en/latest/advanced.html#conditional-rules) but it's written there:

> The if, if-content and if-path attributes can be used with any rule, as well as the <theme /> and <notheme /> directives.

So if it doesn't work that's a bug.

**Comment by loechel** [comment]
@seocam no, the condition works on theme without any problem. 

example:

    <theme href="/theme1.html" if="state2" />
    <theme href="/theme2.html" if="not:state2" />

works without problem if theme1,html and theme2.html is readable. and only one is applyed. But if you call a theme from a remote address which is not readable. Diazo throws an Error even if the condition for the theme is not meet.

In my opinion it is a bug, in the execution order, not in the usage of if itself.

**Comment by seocam** [comment]
@loechel thanks for explaining. I agree, this is a bug.

**Comment by lrowe** [comment]
This is pretty inherent in the way diazo works. Themes are read in at compile time not at run time.

If statements on themes execute at run time to pick which theme to apply.

**Comment by seocam** [comment]
@lrowe in that case I would consider this at least a documentation bug. We could add a note box or something.

**Comment by lrowe** [comment]
Perhaps add the note to this section: http://docs.diazo.org/en/latest/advanced.html#multiple-conditional-themes
