### ISSUE TITLE
Using WebOb 1.7.0 tests are failing

### ISSUE THREAD

**Issue by jensens** [plone/diazo#67]
I just tried to update Plone 5.1 coredev to WebOb 1.7.0. Then some tests are failing with WebOb 1.7.0. With latest 1.6 all is fine. See the 3 Diazo related test failures in http://jenkins.plone.org/job/pull-request-5.1/1118/testReport/junit/

At least one of these is maybe related to the change in https://github.com/Pylons/webob/pull/261

**Comment by gforcada** [comment]
@davisagli fixed that and is already on a release (1.2.5)
